id: IC3F30481
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T08:43:35.946140'
last_modified: '2022-06-19T08:43:35.946151'
parser: null
source_metadata:
  title: Hagiography of the 51st Ngor abbot rNal byor Jam dpal bzang po bkra shis
    grags pai rgyal mtshan (1789–1864); Lamdre Lobshe, vol. ja, title no. 3
  author: byams pa kun dga bstan pai rgyal mtshan/
  description: 'Digital version 2.0 {Wylie}; WYLIE COPY of master xml (completed:
    2013-09-05); unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:rdzong sar khams bye'i lnga rig slob gling / sde dge rdzong sar/ (dzkj)
  - Editorial process:Mathias Fermer (mf), kun dga' rdo rje/ (Kathmandu) (kun)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/580
  bases:
    c9da:
      title: Hagiography of the 51st Ngor abbot rNal byor Jam dpal bzang po bkra shis
        grags pai rgyal mtshan (1789–1864); Lamdre Lobshe, vol. ja, title no. 3
      order: 1
      base_file: c9da.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
